### ISSUE TITLE
Robot localization using aruco marker in gazebo 

### ISSUE THREAD

**Issue by Eswar1991** [pal-robotics/aruco_ros#83] opened 2020-06-25 07:31 UTC
We are trying to localize the robot in gazebo using aruco marker. We have successfully loaded the marker into gazebo, detected it, and obtained the transformation between camera frame and marker frame using aruco_ros (https://github.com/pal-robotics/aruco_ros) package. The transform between them obtained from tf package is in excellent agreement with the one obtained from the package.
![image](https://user-images.githubusercontent.com/16931432/85675996-d411f700-b6e3-11ea-85a5-3fce3bad91f9.png)
However, the physical location of marker frame is not the same when we visualize it in RviZ. Please see the image below
![image](https://user-images.githubusercontent.com/16931432/85676031-dbd19b80-b6e3-11ea-9957-5cc9fdee2c5a.png)
As shown above, the location of marker frame in RViz does not match with that of gazebo. This really confuses us because we are not clear which dictates the physical location of marker in reality

Any help on this issue would be appreciated.
Thanks

**Comment by chebbal** [comment] 2022-05-18 11:03
@Eswar1991 did you find a fix for this issue??

**Comment by saikishor** [comment] 2022-05-19 08:03
Hello @Eswar1991 @chebbal,

 what version are you using for this?, We have recently fixed a bug in the implementation pointed in this issue : https://github.com/pal-robotics/aruco_ros/issues/98. May be this might be the root cause in your case too. Please let us know if this fix fixes your issue.
 
 Thank you,
 
 Best Regards,
 PAL Robotics Team.

**Comment by chebbal** [comment] 2022-05-19 09:33
Hi @saikishor ,

Thanks for the quick revert
In my case the issue was with frame definition, resolved it, it works fine now

regards,
Chaitanya

**Comment by saikishor** [comment] 2022-05-19 09:38
Hello @chebbal ,

Thank you for confirming that, then I will be proceeding to close this issue. 

Thank you,

Best Regards,
PAL Robotics Team

**Closed as completed by saikishor** 2022-05-19 09:38 UTC
